{{- if .Values.secretProviderClass.enabled -}}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  annotations:
    helm.sh/chart: {{ printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
  name: {{ .Release.Name }}-secretproviderclass
  namespace: {{ .Release.Namespace }}
spec:
  provider: azure
  secretObjects:
    - secretName: {{ .Chart.Name }}-{{ .Release.Namespace }}
      type: Opaque
      data:
        - key: DATABASE_URI
          objectName: opennsa-{{ .Release.Namespace }}-db-uri
        - key: DATABASE_NAME
          objectName: opennsa-{{ .Release.Namespace }}-db-name
        - key: DATABASE_PASSWORD
          objectName: opennsa-{{ .Release.Namespace }}-db-password
        - key: DATABASE_USERNAME
          objectName: opennsa-{{ .Release.Namespace }}-db-username
  parameters:
    keyvaultName: {{ .Values.secretProviderClass.keyVaultName }}
    objects: |
      array:
        - |
          objectName: opennsa-{{ .Release.Namespace }}-db-uri
          objectType: secret
        - |
          objectName: opennsa-{{ .Release.Namespace }}-db-name
          objectType: secret
        - |
          objectName: opennsa-{{ .Release.Namespace }}-db-password
          objectType: secret
        - |
          objectName: opennsa-{{ .Release.Namespace }}-db-username
          objectType: secret
    tenantId: {{ .Values.secretProviderClass.tenantId }}
{{- end }}
